2025-05-19 20:19:07,512 INFO    MainThread:63855 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /Users/denisangel2k2/Documents/Github/cnn-encoder/wandb/run-20250519_201907-hqa66i2l/logs/debug.log
2025-05-19 20:19:07,513 INFO    MainThread:63855 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /Users/denisangel2k2/Documents/Github/cnn-encoder/wandb/run-20250519_201907-hqa66i2l/logs/debug-internal.log
2025-05-19 20:19:07,513 INFO    MainThread:63855 [wandb_init.py:init():852] calling init triggers
2025-05-19 20:19:07,513 INFO    MainThread:63855 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'epochs': 10, '_wandb': {}}
2025-05-19 20:19:08,355 INFO    MainThread:63855 [wandb_init.py:init():893] starting backend
2025-05-19 20:19:08,355 INFO    MainThread:63855 [wandb_init.py:init():897] sending inform_init request
2025-05-19 20:19:08,356 INFO    MainThread:63855 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-19 20:19:08,356 INFO    MainThread:63855 [wandb_init.py:init():907] backend started and connected
2025-05-19 20:19:08,366 INFO    MainThread:63855 [wandb_run.py:_label_probe_notebook():1376] probe notebook
2025-05-19 20:19:08,368 INFO    MainThread:63855 [wandb_init.py:init():1005] updated telemetry
2025-05-19 20:19:08,371 INFO    MainThread:63855 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-05-19 20:19:08,982 INFO    MainThread:63855 [wandb_init.py:init():1104] starting run threads in backend
2025-05-19 20:19:09,102 INFO    MainThread:63855 [wandb_run.py:_console_start():2573] atexit reg
2025-05-19 20:19:09,102 INFO    MainThread:63855 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-05-19 20:19:09,102 INFO    MainThread:63855 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-05-19 20:19:09,102 INFO    MainThread:63855 [wandb_run.py:_redirect():2513] Redirects installed.
2025-05-19 20:19:09,103 INFO    MainThread:63855 [wandb_init.py:init():1150] run started, returning control to user process
2025-05-19 20:22:46,368 WARNING MsgRouterThr:63855 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-19 20:22:46,533 INFO    MsgRouterThr:63855 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 8 handles.
2025-05-19 20:22:48,716 INFO    MainThread:63855 [wandb_run.py:_finish():2321] finishing run denismoldovan-babes-bolyai-university/cnn2rnn-translation/hqa66i2l
2025-05-19 20:22:48,716 INFO    MainThread:63855 [wandb_run.py:_atexit_cleanup():2538] got exitcode: 0
2025-05-19 20:22:48,717 INFO    MainThread:63855 [wandb_run.py:_restore():2520] restore
2025-05-19 20:22:48,717 INFO    MainThread:63855 [wandb_run.py:_restore():2526] restore done
2025-05-19 20:22:48,718 INFO    MainThread:63855 [wandb_run.py:_restore():2520] restore
2025-05-19 20:22:48,718 INFO    MainThread:63855 [wandb_run.py:_restore():2526] restore done
2025-05-19 20:22:48,718 ERROR   MainThread:63855 [wandb_run.py:_atexit_cleanup():2559] Problem finishing run
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2550, in _atexit_cleanup
    self._on_finish()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2797, in _on_finish
    exit_handle = self._backend.interface.deliver_exit(self._exit_code)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 1005, in deliver_exit
    return self._deliver_exit(exit_data)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 436, in _deliver_exit
    return self._deliver_record(record)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 389, in _deliver_record
    handle = mailbox.require_response(record)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/mailbox/mailbox.py", line 68, in require_response
    raise MailboxClosedError()
wandb.sdk.mailbox.mailbox.MailboxClosedError
2025-05-19 20:22:48,822 ERROR   MainThread:63855 [wandb_init.py:init():1687] [no run ID] error in wandb.init()
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1677, in init
    return wi.init(run_settings, run_config, run_printer)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 873, in init
    self._wl.finish_all_active_runs()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 152, in finish_all_active_runs
    run.finish()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 503, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 451, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2309, in finish
    return self._finish(exit_code)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2337, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2550, in _atexit_cleanup
    self._on_finish()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2797, in _on_finish
    exit_handle = self._backend.interface.deliver_exit(self._exit_code)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 1005, in deliver_exit
    return self._deliver_exit(exit_data)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 436, in _deliver_exit
    return self._deliver_record(record)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 389, in _deliver_record
    handle = mailbox.require_response(record)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/mailbox/mailbox.py", line 68, in require_response
    raise MailboxClosedError()
wandb.sdk.mailbox.mailbox.MailboxClosedError
2025-05-19 20:23:02,996 ERROR   MainThread:63855 [wandb_init.py:init():1687] [no run ID] error in wandb.init()
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1677, in init
    return wi.init(run_settings, run_config, run_printer)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 898, in init
    service.inform_init(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/lib/service_connection.py", line 151, in inform_init
    self._client.send_server_request(spb.ServerRequest(inform_init=request))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
