2025-05-25 20:42:17,516 INFO    MainThread:10921 [wandb_init.py:setup_run_log_directory():724] Logging user logs to /Users/denisangel2k2/Documents/Github/cnn-encoder/wandb/run-20250525_204217-ib0emdob/logs/debug.log
2025-05-25 20:42:17,516 INFO    MainThread:10921 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to /Users/denisangel2k2/Documents/Github/cnn-encoder/wandb/run-20250525_204217-ib0emdob/logs/debug-internal.log
2025-05-25 20:42:17,516 INFO    MainThread:10921 [wandb_init.py:init():852] calling init triggers
2025-05-25 20:42:17,516 INFO    MainThread:10921 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-25 20:42:18,451 INFO    MainThread:10921 [wandb_init.py:init():893] starting backend
2025-05-25 20:42:18,451 INFO    MainThread:10921 [wandb_init.py:init():897] sending inform_init request
2025-05-25 20:42:18,452 INFO    MainThread:10921 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2025-05-25 20:42:18,452 INFO    MainThread:10921 [wandb_init.py:init():907] backend started and connected
2025-05-25 20:42:18,456 INFO    MainThread:10921 [wandb_run.py:_label_probe_notebook():1376] probe notebook
2025-05-25 20:42:18,457 INFO    MainThread:10921 [wandb_init.py:init():1005] updated telemetry
2025-05-25 20:42:18,556 INFO    MainThread:10921 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-05-25 20:42:18,896 INFO    MainThread:10921 [wandb_init.py:init():1104] starting run threads in backend
2025-05-25 20:42:19,003 INFO    MainThread:10921 [wandb_run.py:_console_start():2573] atexit reg
2025-05-25 20:42:19,003 INFO    MainThread:10921 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-05-25 20:42:19,003 INFO    MainThread:10921 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-05-25 20:42:19,003 INFO    MainThread:10921 [wandb_run.py:_redirect():2513] Redirects installed.
2025-05-25 20:42:19,004 INFO    MainThread:10921 [wandb_init.py:init():1150] run started, returning control to user process
2025-05-25 21:01:53,969 INFO    MainThread:10921 [wandb_run.py:_finish():2321] finishing run denismoldovan-babes-bolyai-university/nmt_training/ib0emdob
2025-05-25 21:01:53,970 INFO    MainThread:10921 [wandb_run.py:_atexit_cleanup():2538] got exitcode: 0
2025-05-25 21:01:53,970 INFO    MainThread:10921 [wandb_run.py:_restore():2520] restore
2025-05-25 21:01:53,970 INFO    MainThread:10921 [wandb_run.py:_restore():2526] restore done
2025-05-25 21:02:21,108 WARNING MainThread:10921 [wandb_init.py:init():1681] [no run ID] interrupted
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 1677, in init
    return wi.init(run_settings, run_config, run_printer)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 873, in init
    self._wl.finish_all_active_runs()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_setup.py", line 152, in finish_all_active_runs
    run.finish()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 503, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 451, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2309, in finish
    return self._finish(exit_code)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2337, in _finish
    self._atexit_cleanup(exit_code=exit_code)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2550, in _atexit_cleanup
    self._on_finish()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/wandb_run.py", line 2806, in _on_finish
    wait_with_progress(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 24, in wait_with_progress
    return wait_all_with_progress(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/mailbox/wait_with_progress.py", line 87, in wait_all_with_progress
    return asyncio_compat.run(progress_loop_with_timeout)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/lib/asyncio_compat.py", line 30, in run
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/concurrent/futures/_base.py", line 441, in result
    self._condition.wait(timeout)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/threading.py", line 312, in wait
    waiter.acquire()
KeyboardInterrupt
2025-05-25 21:02:21,109 WARNING MsgRouterThr:10921 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/lib/sock_client.py", line 220, in _read_packet_bytes
    raise SockClientClosedError
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/router.py", line 56, in message_loop
    msg = self._read_message()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/deeplearning-env/lib/python3.9/site-packages/wandb/sdk/interface/router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-05-25 21:02:21,126 INFO    MsgRouterThr:10921 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 10 handles.
